name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install Task
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Package (macOS) via Taskfile
        run: |
          mkdir -p Release
          chmod +x DistributionTool || true
          task --version
          task package

      - name: Upload artifacts (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-macos
          path: |
            dev.flowingspdg.buttontester.sdPlugin/**
            Release/**

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install Task
        shell: bash
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Package (Windows) via Taskfile
        shell: bash
        run: |
          mkdir -p Release
          task --version
          task package:windows

      - name: Upload artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows
          path: |
            dev.flowingspdg.buttontester.sdPlugin/**
            Release/**


