name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install Task
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Stage plugin via Taskfile (macOS)
        run: |
          task --version
          task prepare
          task build:mac
          task copy:assets
          mkdir -p Release

      - name: Verify bundle (macOS)
        run: |
          echo "--- manifest.json ---"
          cat dev.flowingspdg.buttontester.sdPlugin/manifest.json
          echo "--- bundle listing ---"
          ls -la dev.flowingspdg.buttontester.sdPlugin
          echo "--- checks ---"
          grep -q '"CodePath"' dev.flowingspdg.buttontester.sdPlugin/manifest.json
          test -f dev.flowingspdg.buttontester.sdPlugin/button_tester || (echo "missing mac binary" && exit 1)

      - name: StreamDeck Distribution Tool (macOS)
        uses: AdamCarballo/streamdeck-distribution-tool@v1
        with:
          input: dev.flowingspdg.buttontester.sdPlugin
          output: Release

      - name: Upload artifacts (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-macos
          path: |
            dev.flowingspdg.buttontester.sdPlugin/**
            Release/**

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install Task
        shell: bash
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Stage plugin via Taskfile (Windows)
        shell: bash
        run: |
          task --version
          task prepare
          task build:windows
          task copy:assets
          mkdir -p Release

      - name: Verify bundle (Windows)
        shell: bash
        run: |
          echo "--- manifest.json ---"
          cat dev.flowingspdg.buttontester.sdPlugin/manifest.json
          echo "--- bundle listing ---"
          ls -la dev.flowingspdg.buttontester.sdPlugin
          echo "--- checks ---"
          grep -q '"CodePath"' dev.flowingspdg.buttontester.sdPlugin/manifest.json
          test -f dev.flowingspdg.buttontester.sdPlugin/button_tester.exe || (echo "missing windows binary" && exit 1)

      - name: StreamDeck Distribution Tool (Windows)
        uses: AdamCarballo/streamdeck-distribution-tool@v1
        with:
          input: dev.flowingspdg.buttontester.sdPlugin
          output: Release

      - name: Upload artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows
          path: |
            dev.flowingspdg.buttontester.sdPlugin/**
            Release/**


